# Generated by Django 3.1.4 on 2021-01-17 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledenlijst', '0002_ledenprofiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(blank=True, max_length=300)),
                ('omschrijving', models.TextField(blank=True, max_length=500)),
                ('contactpersoon', models.CharField(blank=True, max_length=200)),
                ('straatnaam', models.CharField(blank=True, max_length=300)),
                ('postcode', models.CharField(blank=True, max_length=7)),
                ('plaats', models.CharField(blank=True, max_length=100)),
                ('telefoonnummer', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('foto', models.ImageField(blank=True, upload_to='fotos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ledenprofiel',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LedenLijst',
        ),
        migrations.DeleteModel(
            name='LedenProfiel',
        ),
    ]
